### ISSUE TITLE
Enron: Trying to update memory to time in the past

### ISSUE THREAD

**Issue by manuel-dileo** [fpour/DGB#4]
Hi and thank you for your work again :D

I'm trying to reproduce the results of your experiments on the Enron dataset. I downloaded the dataset from Zenodo and performed all the preprocessing steps as described. 

When I run from the terminal the following script:

```
data=enron
n_runs=3

# JODIE
method=jodie
prefix="${method}_rnn"
python train_self_supervised.py -d $data --use_memory --memory_updater rnn --embedding_module time --prefix "$prefix" --n_runs "$n_runs" --gpu 0 --decoder concat
```

I obtain the following error:

```
INFO:root:Namespace(data='enron', decoder='concat', bs=200, prefix='jodie_rnn', n_degree=10, n_head=2, n_epoch=50, n_layer=1, lr=0.0001, patience=5, n_runs=3, drop_out=0.1, gpu=0, node_dim=100, time_dim=100, backprop_every=1, use_memory=True, embedding_module='time', message_function='identity', memory_updater='rnn', aggregator='last', memory_update_at_end=False, message_dim=100, memory_dim=172, different_new_nodes=False, uniform=False, randomize_features=False, use_destination_embedding_in_message=False, use_source_embedding_in_message=False, dyrep=False, val_ratio=0.15, test_ratio=0.15)
The dataset has 125235 interactions, involving 125235 different nodes
The training dataset has 64075 interactions, involving 64141 different nodes
The validation dataset has 17778 interactions, involving 17879 different nodes
The test dataset has 17983 interactions, involving 18065 different nodes
The new node validation dataset has 17751 interactions, involving 17871 different nodes
The new node test dataset has 17948 interactions, involving 18056 different nodes
12523 nodes were used for the inductive testing, i.e. are never seen during training
INFO:root:************************************
INFO:root:********** Run 0 starts. **********
INFO:root:num of training instances: 64075
INFO:root:num of batches per epoch: 321
INFO:root:start 0 epoch
Traceback (most recent call last):
  File "/home/jupyter-manuel/DGB/tgn/train_self_supervised.py", line 233, in <module>
    neg_prob = tgn.compute_edge_probabilities_modified(sources_batch, negatives_batch, timestamps_batch,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jupyter-manuel/DGB/tgn/model/tgn.py", line 339, in compute_edge_probabilities_modified
    source_node_embedding, destination_node_embedding = self.compute_temporal_embeddings_modified(
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jupyter-manuel/DGB/tgn/model/tgn.py", line 232, in compute_temporal_embeddings_modified
    memory, last_update = self.get_updated_memory(list(range(self.n_nodes)),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jupyter-manuel/DGB/tgn/model/tgn.py", line 382, in get_updated_memory
    updated_memory, updated_last_update = self.memory_updater.get_updated_memory(unique_nodes,
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jupyter-manuel/DGB/tgn/modules/memory_updater.py", line 36, in get_updated_memory
    assert (self.memory.get_last_update(unique_node_ids) <= timestamps).all().item(), "Trying to " \
AssertionError: Trying to update memory to time in the past
```

What could be causing this error? On other datasets like Wikipedia or CanParl, following the same preprocessing steps, the package works perfectly.

Thank you in advance for your help and feel free to request any further details.

**Comment by manuel-dileo** [comment]
Ok, this error seems related to the absence of the enron.csv file in the Zenodo datasets zip. If the "ml" files are used directly without running preprocessing_data.py it works at least for the tgn-based models. Where can I find the <network>.csv files related to enron and uci-social?

**Comment by fpour** [comment]
Hi,
Thanks for point this issue to our attention. Unfortunately, as Enron is not one of our contributed datasets, we don't have access to the original file of the datasets. You can check here: [https://www.cs.cmu.edu/~./enron/](https://www.cs.cmu.edu/~./enron/) for more information about this dataset.
